---
title: "Weather"
author: "Alliyah Galvan & Jason Nguyen"
date: "March 13, 2020"
output: ioslides_presentation
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library("skimr")
library("tidyverse")
library("naniar")
library("shiny")
library("shinydashboard")
```

```{r include=FALSE}
weather <- read_csv("data/Weather.csv")
```

```{r include=FALSE}
new_factor<- c(1:5,26)
new_numeric<- c(6:25)
weather[,new_factor] <- lapply(weather[,new_factor], as.factor)
weather[,new_numeric] <- lapply(weather[,new_numeric], as.numeric)
lapply(weather, class) #changing classes
```

## BACKGROUND

# Shiny App

```{r include=FALSE}
weather_temp <- weather %>% 
  select(year, city, avg_temp) %>% 
  group_by(city, year) %>%
  summarize(Average_Temp=mean(avg_temp)) %>%
  rename(City="city", Year="year")
```

```{r include=FALSE}
weather_dewpt <-weather %>% 
  select(year, city, avg_dewpt) %>% 
  group_by(city, year) %>%
  summarize(Average_Dew_Point=mean(avg_dewpt)) %>% 
  select(-c("year"))
```

```{r include=FALSE}
weather_humidty <- weather %>% 
  select(year, city, avg_humidity) %>% 
  group_by(city, year) %>%
  summarize(Average_Humidty=mean(avg_humidity)) %>%
  select(-c("year"))
```

```{r include=FALSE}
weather_wind <- weather %>% 
  select(year, city, avg_wind) %>% 
  group_by(city, year) %>%
  summarize(Average_Wind=mean(avg_wind)) %>%
  select(-c("year"))
```

```{r results= 'hide', character}
weather_mean <- cbind(weather_temp, weather_dewpt, weather_humidty, weather_wind) #combining yearly average into one table
weather_cleaner <- weather_mean %>% 
  select(-c(4,6,8)) %>% 
  pivot_longer(Average_Temp:Average_Wind,
               names_to = "Measure",
               values_to = "Value")
weather_cleaner
```

## **Average Monthly Temperatures for All Cities for 2016**
```{r echo=FALSE}
weather %>% 
  mutate_at(vars(month), as.factor) %>% 
 filter(year== 2016) %>%
  group_by(month, city) %>% 
  summarize(mean_avgtemp=mean(avg_temp))  %>% 
  ggplot(aes(x=month, y=mean_avgtemp, color=city, group=city))+
  geom_line() +
  geom_point(alpha=0.8)+
  labs(title="2016 Monthly Average Temperature",
       x= "Month",
       y="Average Temp") +
  theme(plot.title = element_text(size = 18, face = "bold"),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12))
```

## **Average Monthly Temperatures for All Cities for 2017**
```{r echo=FALSE}
weather %>% 
  mutate_at(vars(month), as.factor) %>% 
 filter(year== 2017) %>%
  group_by(month, city) %>% 
  summarize(mean_avgtemp=mean(avg_temp))  %>% 
  ggplot(aes(x=month, y=mean_avgtemp, color=city, group=city))+
  geom_line() +
  geom_point(alpha=0.8)+
  labs(title="2017 Monthly Average Temperature",
       x= "Month",
       y="Average Temp") +
  theme(plot.title = element_text(size = 18, face = "bold"),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12))
```

## **Average Monthly Dewpoints for All Cities for 2016**
```{r echo=FALSE}
weather %>% 
  mutate_at(vars(month), as.factor) %>% 
 filter(year== 2016) %>%
  group_by(month, city) %>% 
  summarize(mean_avgdewpt=mean(avg_dewpt))  %>% 
  ggplot(aes(x=month, y=mean_avgdewpt, color=city, group=city))+
  geom_line() +
  geom_point(alpha=0.8)+
  labs(title="2016 Monthly Average Dewpoint",
       x= "Month",
       y="Average Dewpoint") +
  theme(plot.title = element_text(size = 18, face = "bold"),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12))
```

## **Average Monthly Dewpoints for All Cities for 2017**
```{r echo=FALSE}
weather %>% 
  mutate_at(vars(month), as.factor) %>% 
 filter(year== 2017) %>%
  group_by(month, city) %>% 
  summarize(mean_avgdewpt=mean(avg_dewpt))  %>% 
  ggplot(aes(x=month, y=mean_avgdewpt, color=city, group=city))+
  geom_line() +
  geom_point(alpha=0.8)+
  labs(title="2017 Monthly Average Dewpoint",
       x= "Month",
       y="Average Dewpoint") +
  theme(plot.title = element_text(size = 18, face = "bold"),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12))
```

## **Average Monthly Humidity for All Cities for 2016**
```{r echo=FALSE}
weather %>% 
  mutate_at(vars(month), as.factor) %>% 
 filter(year== 2016) %>%
  group_by(month, city) %>% 
  summarize(mean_avghumidity=mean(avg_humidity))  %>% 
  ggplot(aes(x=month, y=mean_avghumidity, color=city, group=city))+
  geom_line() +
  geom_point(alpha=0.8)+
  labs(title="2016 Monthly Average Humidity",
       x= "Month",
       y="Average Humidity") +
  theme(plot.title = element_text(size = 18, face = "bold"),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12))
```

## **Average Monthly Humidity for All Cities for 2017**
```{r echo=FALSE}
weather %>% 
  mutate_at(vars(month), as.factor) %>% 
 filter(year== 2017) %>%
  group_by(month, city) %>% 
  summarize(mean_avghumidity=mean(avg_humidity))  %>% 
  ggplot(aes(x=month, y=mean_avghumidity, color=city, group=city))+
  geom_line() +
  geom_point(alpha=0.8)+
  labs(title="2017 Monthly Average Humidity",
       x= "Month",
       y="Average Humidity") +
  theme(plot.title = element_text(size = 18, face = "bold"),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12))
```