---
title: "Weather"
author: "Alliyah Galvan & Jason Nguyen"
date: "March 9, 2020"
output:
  html_document: 
    keep_md: yes
    theme: spacelab
    toc: yes
    toc_float: yes
---

```{r}
library(tidyverse)
library(naniar)
library(skimr)
```

```{r}
weather <- readr::read_csv("data/weather.csv")
weather
```

```{r}
weather %>% 
  select(-"X1")
```

```{r}
glimpse(weather)
```

```{r}
colnames(weather)
```

```{r}
new_factor<- c(1:5,26)
new_numeric<- c(6:25)
weather[,new_factor] <- lapply(weather[,new_factor], as.factor)
weather[,new_numeric] <- lapply(weather[,new_numeric], as.numeric)
lapply(weather, class) #changing classes
```

## The Average Temperature of Each City in 2016.

```{r}
weather %>% 
  filter(year=="2017") %>% 
  select(city, avg_temp) %>% 
  group_by(city) %>%
  summarize(yearly_avg_temp=mean(avg_temp))
```

```{r}
weather %>%
  filter(year=="2017") %>% 
  group_by(city) %>%
  summarize(yearly_avg_temp=mean(avg_temp)) %>% 
  ggplot(aes(x=city, yearly_avg_temp)) +
  geom_bar(stat = "identity")
```

## Weather Events by City

```{r}
weather$events<- as.character(weather$events)
weather$events[is.na(weather$events)] <- "Clear Skies"
```

```{r}
skies <- weather %>% 
  select(city, events)
```

```{r}
skies %>%
  filter(city== "Auckland") %>% 
  ggplot(aes(x=events)) +
  geom_bar(fill = "brown1", color="black", alpha =.5) +
  labs(title = "Weather Events in Auckland",
       x= "Weather Events",
       y= "Count") +
  theme(plot.title = element_text(size = 18, face = "bold", hjust = 0.5),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 15),)+
  coord_flip()
```

```{r}
skies %>%
  filter(city== "Beijing") %>% 
  ggplot(aes(x=events)) +
  geom_bar(fill = "darkgoldenrod2", color="black", alpha =.5) +
  labs(title = "Weather Events in Beijing",
       x= "Weather Events",
       y= "Count") +
  theme(plot.title = element_text(size = 18, face = "bold", hjust = 0.5),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 15),)+
  coord_flip()
```

```{r}
skies %>%
  filter(city== "Chicago") %>% 
  ggplot(aes(x=events)) +
  geom_bar(fill = "palegreen1", color="black", alpha =.5) +
  labs(title = "Weather Events in Chicago",
       x= "Weather Events",
       y= "Count") +
  theme(plot.title = element_text(size = 18, face = "bold", hjust = 0.5),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 15),)+
  coord_flip()
```

```{r}
skies %>%
  filter(city== "Mumbai") %>% 
  ggplot(aes(x=events)) +
  geom_bar(fill = "deepskyblue", color="black", alpha =.5) +
  labs(title = "Weather Events in Mumbai",
       x= "Weather Events",
       y= "Count") +
  theme(plot.title = element_text(size = 18, face = "bold", hjust = 0.5),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 15),)+
  coord_flip()
```

```{r}
skies %>%
  filter(city== "San Diego") %>% 
  ggplot(aes(x=events)) +
  geom_bar(fill = "magenta", color="black", alpha =.5) +
  labs(title = "Weather Events in San D",
       x= "Weather Events",
       y= "Count") +
  theme(plot.title = element_text(size = 18, face = "bold", hjust = 0.5),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 15),)+
  coord_flip()
```
